/**
 * @file icon.h
 * @brief Icon type wrapping the pre-rasterized bitmap variants generated by scripts/gen_assets.py.
 */
#ifndef ICON_H
#define ICON_H

#include <Arduino.h>

/// One concrete bitmap of an Icon, picked out at a specific pixel size.
class ScaledIcon {
   public:
    /**
     * @brief Wrap a bitmap and the pixel size it was rasterized at.
     * @param data Raw bitmap data, in the format expected by `display.drawBitmap()`.
     * @param size Width/height in pixels (icons are always square).
     */
    ScaledIcon(const unsigned char *data, uint16_t size) : data(data), size(size) {}

    const unsigned char *data;  ///< Raw bitmap data.
    uint16_t size;              ///< Width/height in pixels.
};

/**
 * @brief A square icon pre-rasterized at four fixed sizes.
 *
 * Only 192/128/64/48px variants exist (generated ahead of time, since the ESP32 has no
 * runtime image-scaling); scaled() picks the matching bitmap rather than resizing on the fly.
 */
class Icon {
   public:
    /**
     * @brief Wrap the four pre-rasterized bitmap variants of one icon.
     * @param icon192 Bitmap at 192x192px.
     * @param icon128 Bitmap at 128x128px.
     * @param icon64 Bitmap at 64x64px.
     * @param icon48 Bitmap at 48x48px.
     */
    Icon(const unsigned char *icon192, const unsigned char *icon128, const unsigned char *icon64,
         const unsigned char *icon48)
        : icon192(icon192), icon128(icon128), icon64(icon64), icon48(icon48) {}

    const unsigned char *icon192;  ///< Bitmap at 192x192px.
    const unsigned char *icon128;  ///< Bitmap at 128x128px.
    const unsigned char *icon64;   ///< Bitmap at 64x64px.
    const unsigned char *icon48;   ///< Bitmap at 48x48px.

    /**
     * @brief Look up the pre-rasterized bitmap for a given size.
     * @param size One of 192, 128, 64, or 48. Any other value falls back to the 48px bitmap.
     * @return The matching ScaledIcon.
     */
    ScaledIcon scaled(uint16_t size) {
        switch (size) {
            case 192:
                return ScaledIcon(icon192, 192);
            case 128:
                return ScaledIcon(icon128, 128);
            case 64:
                return ScaledIcon(icon64, 64);
            case 48:
                return ScaledIcon(icon48, 48);
            default:
                return ScaledIcon(icon48, 48);
        }
    }
};

#endif  // ICON_H